version: '3'
services:
  postgres:
    image: postgres:16.0
    ports:
      - 5432:5432
    environment:
      - name=value
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=postgres 
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata     
    container_name: postgres-db
    volumes:
      - ./scripts:/scripts
      - ./postgres-data:/var/lib/postgresql/data/pgdata
      - ./init-migrations:/docker-entrypoint-initdb.d
